spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica
    username: seu_nome_de_usuario
    password: sua_senha
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
#       para criar o bco: executa somenta a primeira vez " ddl-auto: create ", depois troca de create pora "validate"


#    spring:
#      datasource:
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:50653}/${MYSQL_DATABASE:railway}
#        username: ${MYSQL_USER:MYSQLUSER}
#        password: ${MYSQL_PASSWORD:MYSQLPASSWORD}
#      jpa:
#        open-in-view: false
#        hibernate:
#          ddl-auto: create
#        database-platform: org.hibernate.dialect.MySQLDialect
#
#    flyway:
#      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:MYSQLDATABASE}
#      user: ${MYSQL_USER:MYSQLUSER}
#      password: ${MYSQL_PASSWORD:MYSQLPASSWORD}

